spring:
  profiles:
    active: dev # 默认激活 dev，可在部署时使用 prod 替换

server:
  port: 9002
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:ezpK30egWVnRIlIu0WsTvLUZ1JRfWajod5cRj9EV7k4=}
  expiration: ${JWT_EXPIRATION:86400000}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    group: 'default'
    paths-to-match: '/**'
    packages-to-scan: com.shiyuan.base

knife4j:
  enable: true
  setting:
    language: zh-CN
    enable-swagger-models: true
    enable-document-manage: true
    swagger-model-name: 实体类列表
